services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      FLASK_SECRET_KEY: "predprof2026"
      CANTEEN_DB: "/data/canteen.db"
      CANTEEN_REPORTS_DIR: "/data/reports"
      WORKERS: "1"
      THREADS: "4"
      TIMEOUT: "120"
    volumes:
      - ./data:/data
    restart: unless-stopped
